# ==========================================
# CONFIGURAÇÃO DO BANCO DE DADOS
# ==========================================

# URL de conexão com o MySQL
# localhost:3308 = porta exposta pelo Docker
# /agenda = nome do banco de dados
spring.datasource.url=jdbc:mysql://localhost:3308/agenda

# Driver JDBC do MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ==========================================
# JPA / HIBERNATE
# ==========================================

# Atualiza automaticamente as tabelas conforme suas entidades
# Se a tabela não existir, ela será criada.
# Se você adicionar/modificar uma coluna, o Hibernate tenta atualizar.
spring.jpa.hibernate.ddl-auto=update

# Mostra no console os SQLs executados pelo Hibernate
spring.jpa.show-sql=true

# Formata os SQLs no console para ficarem mais legíveis
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Porta onde sua aplicação Spring Boot vai rodar
server.port=8080